[tool.poetry]
name = "clovers-leafgame"
version = "0.2.0"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.0"
matplotlib = "^3.9.1.post1"
mplfinance = "^0.12.10b0"
clovers = {extras = ["all"], version = "^0.3.0"}
clovers-apscheduler = "^0.2.0"
clovers-utils = "^0.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
